In [40]:
import pandas as pd
import tensorflow as tf

In [27]:
# lemonade

file_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'

lemonade = pd.read_csv(file_path)

temp = lemonade[['온도']]
total = lemonade[['판매량']]

# print(lemonade.head()) # 상위 5개 
# print(lemonade.shape)
# print(lemonade.columns)

x = tf.keras.layers.Input(shape=[1]) # 독립변수의 열에 맞춰서
y = tf.keras.layers.Dense(1)(x)
model = tf.keras.models.Model(x, y)
model.compile(loss='mse')

model.fit(temp, total, epochs=10000, verbose=0) # verbose = 0 하면 출력 안함


In [30]:
# 만들어진 모델로 예측

print(model.predict(temp))
print(model.predict([[12]]))

[[40.02848 ]
 [42.02213 ]
 [44.015774]
 [46.00942 ]
 [48.003063]
 [49.996708]]
[[24.079317]]


In [36]:
# boston

file_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'

boston = pd.read_csv(file_path)
args = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
medv = boston[['medv']]

# print(boston.columns)


x = tf.keras.layers.Input(shape=[13])
y = tf.keras.layers.Dense(1)(x)

model = tf.keras.models.Model(x, y)
model.compile(loss='mse')

model.fit(args, medv, epochs=1000, verbose=0)
model.fit(args, medv, epochs=10)


Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 26.8903
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 26.1154
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 26.2855
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 26.1618
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 26.5257
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 26.3087
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 26.4094
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 26.5908
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 26.7580
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 25.9408


In [37]:
print(model.predict(args[5:10]))
print(medv[5:10])

[[27.240393 ]
 [22.32729  ]
 [19.292307 ]
 [10.6482315]
 [18.929764 ]]
   medv
5  28.7
6  22.9
7  27.1
8  16.5
9  18.9


In [38]:
print(model.get_weights())

[array([[-0.08575389],
       [ 0.070659  ],
       [-0.05017478],
       [ 3.392261  ],
       [ 1.7456608 ],
       [ 3.9013145 ],
       [ 0.01982425],
       [-0.82517725],
       [ 0.15340585],
       [-0.00772255],
       [-0.00771276],
       [ 0.01718756],
       [-0.5862662 ]], dtype=float32), array([2.9849796], dtype=float32)]


In [61]:
# iris

file_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'

iris = pd.read_csv(file_path)
iris = pd.get_dummies(iris)

args = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dependent = iris[['품종_setosa', '품종_versicolor', '품종_virginica']] # 위 예제와는 다른 범주형 데이터 -> 분류

x = tf.keras.layers.Input(shape=[4])
y = tf.keras.layers.Dense(3, activation='softmax')(x)

model = tf.keras.models.Model(x, y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

model.fit(args, dependent, epochs=700, verbose=0)
model.fit(args, dependent, epochs=10)


Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.2008 - accuracy: 0.9733
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.2008 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.2011 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1999 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.2001 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1995 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1994 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1992 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1997 - accuracy: 0.9733
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1987 - accuracy: 0.9800


In [63]:
print(model.predict(args[:10]))
print(dependent[:10])

[[9.9502230e-01 4.9742409e-03 3.4954003e-06]
 [9.8278058e-01 1.7197894e-02 2.1609050e-05]
 [9.9229807e-01 7.6931622e-03 8.7777889e-06]
 [9.8473084e-01 1.5242699e-02 2.6377489e-05]
 [9.9627942e-01 3.7179668e-03 2.6468238e-06]
 [9.9475729e-01 5.2378648e-03 4.8034203e-06]
 [9.9344856e-01 6.5413928e-03 1.0101882e-05]
 [9.9211991e-01 7.8726886e-03 7.4234335e-06]
 [9.8073739e-01 1.9221060e-02 4.1479692e-05]
 [9.8579526e-01 1.4190205e-02 1.4548635e-05]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
5          1              0             0
6          1              0             0
7          1              0             0
8          1              0             0
9          1              0             0


In [64]:
# hidden layer

file_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'

boston = pd.read_csv(file_path)
args = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
medv = boston[['medv']]

print(args.shape, medv.shape)

(506, 13) (506, 1)


In [73]:
x = tf.keras.layers.Input(shape=[13])
h = tf.keras.layers.Dense(10, activation='swish')(x)
h = tf.keras.layers.Dense(10, activation='swish')(h)
h = tf.keras.layers.Dense(10, activation='swish')(h)
y = tf.keras.layers.Dense(1)(h)

model = tf.keras.models.Model(x, y)
model.compile(loss='mse')

In [74]:
model.summary() # param -> (가중치 w 13개 + b 1개) * 10, w 10개 b 1개 

Model: "model_23"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_24 (InputLayer)        [(None, 13)]              0         
_________________________________________________________________
dense_24 (Dense)             (None, 10)                140       
_________________________________________________________________
dense_25 (Dense)             (None, 10)                110       
_________________________________________________________________
dense_26 (Dense)             (None, 10)                110       
_________________________________________________________________
dense_27 (Dense)             (None, 1)                 11        
Total params: 371
Trainable params: 371
Non-trainable params: 0
_________________________________________________________________


In [75]:
model.fit(args, medv, epochs=1000, verbose=0)
model.fit(args, medv, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 12.5637
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 12.5852
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 11.9265
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 13.2738
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 12.1639
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 12.4456
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 12.2402
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 13.4308
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 12.3429
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 13.2604


In [76]:
print(model.predict(args[:10]))
print(medv[:10])

[[32.402786]
 [21.868214]
 [29.75782 ]
 [35.568455]
 [31.110481]
 [29.633266]
 [20.848156]
 [17.227358]
 [14.842763]
 [17.687088]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2
5  28.7
6  22.9
7  27.1
8  16.5
9  18.9


In [77]:
file_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'

iris = pd.read_csv(file_path)
iris = pd.get_dummies(iris)

args = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dependent = iris[['품종_setosa', '품종_versicolor', '품종_virginica']]

In [79]:
x = tf.keras.layers.Input(shape=[4])
h = tf.keras.layers.Dense(8, activation='swish')(x)
h = tf.keras.layers.Dense(8, activation='swish')(h)
h = tf.keras.layers.Dense(8, activation='swish')(h)
y = tf.keras.layers.Dense(3, activation='softmax')(h)

model = tf.keras.models.Model(x, y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [82]:
print(model.summary())

Model: "model_25"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_26 (InputLayer)        [(None, 4)]               0         
_________________________________________________________________
dense_32 (Dense)             (None, 8)                 40        
_________________________________________________________________
dense_33 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_34 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_35 (Dense)             (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________
None


In [83]:
model.fit(args, dependent, epochs=100)

Epoch 1/100
5/5 [==============================] - 1s 3ms/step - loss: 1.1463 - accuracy: 0.3333
Epoch 2/100
5/5 [==============================] - 0s 5ms/step - loss: 1.1293 - accuracy: 0.3333
Epoch 3/100
5/5 [==============================] - 0s 4ms/step - loss: 1.1163 - accuracy: 0.3333
Epoch 4/100
5/5 [==============================] - 0s 3ms/step - loss: 1.1074 - accuracy: 0.3333
Epoch 5/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0974 - accuracy: 0.3333
Epoch 6/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0867 - accuracy: 0.4600
Epoch 7/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0755 - accuracy: 0.6267
Epoch 8/100
5/5 [==============================] - 0s 4ms/step - loss: 1.0625 - accuracy: 0.6667
Epoch 9/100
5/5 [==============================] - 0s 6ms/step - loss: 1.0473 - accuracy: 0.6667
Epoch 10/100
5/5 [==============================] - 0s 3ms/step - loss: 1.0303 - accuracy: 0.6667
Epoch 11/100
5/5 [===========

In [84]:
print(model.predict(args[10:20]))
print(dependent[10:20])

[[9.9995100e-01 4.9006172e-05 4.5284992e-10]
 [9.9960035e-01 3.9964492e-04 1.2761302e-08]
 [9.9973768e-01 2.6228308e-04 8.8070156e-09]
 [9.9983072e-01 1.6921104e-04 1.0921147e-08]
 [9.9999630e-01 3.6461349e-06 1.2442498e-11]
 [9.9998236e-01 1.7640168e-05 7.4091649e-11]
 [9.9996150e-01 3.8552793e-05 3.0344421e-10]
 [9.9985778e-01 1.4216495e-04 2.3511224e-09]
 [9.9990392e-01 9.6052936e-05 6.0859595e-10]
 [9.9989164e-01 1.0830507e-04 1.6310454e-09]]
    품종_setosa  품종_versicolor  품종_virginica
10          1              0             0
11          1              0             0
12          1              0             0
13          1              0             0
14          1              0             0
15          1              0             0
16          1              0             0
17          1              0             0
18          1              0             0
19          1              0             0


In [86]:
# 숫자로 된 범주형 데이터 다루기

file_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris2.csv'

iris = pd.read_csv(file_path)
print(iris.dtypes)

꽃잎길이     float64
꽃잎폭      float64
꽃받침길이    float64
꽃받침폭     float64
품종         int64
dtype: object


In [90]:
iris['품종'] = iris['품종'].astype('category')
print(iris.dtypes)

꽃잎길이      float64
꽃잎폭       float64
꽃받침길이     float64
꽃받침폭      float64
품종       category
dtype: object


In [92]:
iris = pd.get_dummies(iris)
print(iris[:10])

   꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_0  품종_1  품종_2
0   5.1  3.5    1.4   0.2     1     0     0
1   4.9  3.0    1.4   0.2     1     0     0
2   4.7  3.2    1.3   0.2     1     0     0
3   4.6  3.1    1.5   0.2     1     0     0
4   5.0  3.6    1.4   0.2     1     0     0
5   5.4  3.9    1.7   0.4     1     0     0
6   4.6  3.4    1.4   0.3     1     0     0
7   5.0  3.4    1.5   0.2     1     0     0
8   4.4  2.9    1.4   0.2     1     0     0
9   4.9  3.1    1.5   0.1     1     0     0


In [94]:
print(iris.isna().sum())
iris.tail()

꽃잎길이     0
꽃잎폭      1
꽃받침길이    0
꽃받침폭     0
품종_0     0
품종_1     0
품종_2     0
dtype: int64


꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_0  품종_1  품종_2
145   6.7  3.0    5.2   2.3     0     0     1
146   6.3  2.5    5.0   1.9     0     0     1
147   6.5  3.0    5.2   2.0     0     0     1
148   6.2  3.4    5.4   2.3     0     0     1
149   5.9  NaN    5.1   1.8     0     0     1

In [95]:
mean = iris["꽃잎폭"].mean()
iris["꽃잎폭"] = iris["꽃잎폭"].fillna(mean) # 빈 값을 평균값으로 채움
iris.tail()

꽃잎길이       꽃잎폭  꽃받침길이  꽃받침폭  품종_0  품종_1  품종_2
145   6.7  3.000000    5.2   2.3     0     0     1
146   6.3  2.500000    5.0   1.9     0     0     1
147   6.5  3.000000    5.2   2.0     0     0     1
148   6.2  3.400000    5.4   2.3     0     0     1
149   5.9  3.054362    5.1   1.8     0     0     1

In [97]:

file_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'

boston = pd.read_csv(file_path)
args = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
medv = boston[['medv']]

x = tf.keras.layers.Input(shape=[13])
h = tf.keras.layers.Dense(10)(x)
h = tf.keras.layers.BatchNormalization()(h)
h = tf.keras.layers.Activation('swish')(h)

h = tf.keras.layers.Dense(10)(h)
h = tf.keras.layers.BatchNormalization()(h)
h = tf.keras.layers.Activation('swish')(h)

h = tf.keras.layers.Dense(10)(h)
h = tf.keras.layers.BatchNormalization()(h)
h = tf.keras.layers.Activation('swish')(h)

y = tf.keras.layers.Dense(1)(h)

model = tf.keras.models.Model(x, y)
model.compile(loss='mse')

model.fit(args, medv, epochs=1000, verbose=0)
model.fit(args, medv, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 2ms/step - loss: 9.0409
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 10.3962
Epoch 3/10
16/16 [==============================] - 0s 3ms/step - loss: 9.3767
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 9.3931
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 8.9257
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 12.4582
Epoch 7/10
16/16 [==============================] - 0s 3ms/step - loss: 7.0556
Epoch 8/10
16/16 [==============================] - 0s 4ms/step - loss: 10.3727
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 10.0742
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 11.1074


In [98]:
print(model.predict(args[10:20]))
print(medv[10:20])

[[20.396338]
 [20.198847]
 [21.990576]
 [18.391132]
 [16.851564]
 [18.472002]
 [21.476955]
 [17.11335 ]
 [19.264212]
 [17.42292 ]]
    medv
10  15.0
11  18.9
12  21.7
13  20.4
14  18.2
15  19.9
16  23.1
17  17.5
18  20.2
19  18.2


In [100]:
file_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'

iris = pd.read_csv(file_path)
iris = pd.get_dummies(iris)

args = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dependent = iris[['품종_setosa', '품종_versicolor', '품종_virginica']]
x = tf.keras.layers.Input(shape=[4])
h = tf.keras.layers.Dense(8)(x)
h = tf.keras.layers.BatchNormalization()(h)
h = tf.keras.layers.Activation('swish')(h)

h = tf.keras.layers.Dense(8)(h)
h = tf.keras.layers.BatchNormalization()(h)
h = tf.keras.layers.Activation('swish')(h)

h = tf.keras.layers.Dense(8)(h)
h = tf.keras.layers.BatchNormalization()(h)
h = tf.keras.layers.Activation('swish')(h)

y = tf.keras.layers.Dense(3, activation='softmax')(h)

model = tf.keras.models.Model(x, y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')



In [106]:
model.fit(args, dependent, epochs=999, verbose=0)
model.fit(args, dependent, epochs=1)

5/5 [==============================] - 0s 3ms/step - loss: 0.1314 - accuracy: 0.9600


In [107]:
print(model.predict(args[:10]))
print(dependent[:10])

[[1.00000000e+00 1.30162174e-11 1.21433211e-16]
 [1.00000000e+00 6.16161622e-10 8.68643604e-14]
 [1.00000000e+00 1.30900429e-10 1.53660561e-17]
 [1.00000000e+00 2.23598420e-08 1.16183655e-14]
 [1.00000000e+00 9.28883099e-12 1.55869216e-16]
 [1.00000000e+00 1.07505083e-09 8.89405669e-14]
 [1.00000000e+00 4.27648845e-12 2.53507908e-16]
 [1.00000000e+00 6.23647134e-10 3.36326925e-15]
 [9.99999881e-01 1.04147709e-07 1.97678665e-15]
 [1.00000000e+00 9.13338294e-09 9.51191234e-14]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
5          1              0             0
6          1              0             0
7          1              0             0
8          1              0             0
9          1              0             0
